spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_ruiji
    username: root
    password: 8787521
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    # redis服务所在设备的ip地址
    host: 192.168.59.130
    # redis服务的默认端口号
    port: 6379
    # 登录redis服务的密码
    password: 8787521
    # 指定操作的是0号数据库
    database: 0
    jedis:
      # 连接池相关配置
      pool:
        # 设置最大连接数
        max-active: 8
        # 设置连接池的最大阻塞等待时间
        max-wait: 1ms
        # 设置连接池的最大空闲连接
        max-idle: 4
        # 设置连接池的最小空闲连接
        min-idle: 0
#  main:
#    banner-mode: off
# mybatisPlus的相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    banner: off
    db-config:
      id-type: assign_id
# Spring事务管理日志记录开关
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
server:
  port: 8080

